google_sheet:
  sheet_id: "1NYaPZ9phjmigWajB9YPPFtN8yxn371Ux--HjcSMS8M0"
  worksheet_name: "Cert_Status"

snowflake:
  warehouse: "LAB_S_WH"
  database: "SSINGHAL"
  schema: "POC"
  role: "PYTHON_SERVICE_PRD"
  table_name: "DE_CERT_STATUS"